import pandas as pd
from analysis.exploratory_analysis.constants_exploratory_analysis import SELECTED_PROVINCES, ORDERED_DAMAGE_LEVELS
from analysis.exploratory_analysis.marginal_probabilities.plot_marginal_probabilities import plot
import matplotlib.pyplot as plt